name: build release 

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: builds
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    permissions:
      contents: write

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc
          dub: latest

      - name: install ncurses
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install ncurses
            mkdir -p /usr/local/opt/ncurses
            ln -s /opt/homebrew/opt/ncurses/lib /usr/local/opt/ncurses/lib
          fi  

      - name: build executable
        shell: bash
        run: ./release.sh

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: releases/dtimer-*.tar.gz
